name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to run against. This trigger runs the GoReleaser and MSI builder.
        required: true

jobs:
  release:
    name: release
    strategy:
      # the goreleaser and the Github release API doesn't handle concurrent
      # access well, so run goreleaser serially
      max-parallel: 1
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-22.04
          - macos-latest
    runs-on: ${{ matrix.os }}
    permissions: write-all
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.tag }}

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Install dependency required for linux builds
        if: matrix.os == 'ubuntu-22.04'
        run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Add Lowercase Repository Name to Environment
        run: |
          echo REPOSITORY_NAME_LOWERCASE=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - uses: "docker/login-action@v3"
        if: matrix.os == 'ubuntu-22.04'
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean --config .goreleaser.${{ matrix.os }}.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMAGE_NAME: ${{ env.REPOSITORY_NAME_LOWERCASE }}
